[package]
name = "tokio_tcp_1_41"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { package = "tokio", version = "=1.41.1", features = ["full"] }
rand = "0.8"
log = "0.4.20"
